name: CustomCraft-Plugin
version: 1.0
main: com.nonkungch.customcraft.CustomCraft
author: nonkungch
api-version: 1.21  # <-- อัปเดต: รองรับ 1.21+

commands:
  customcraft:
    description: Opens the custom crafting menu.
    aliases: [cc]
    usage: /customcraft
  ccadmin:
    description: Administration command for custom recipes.
    permission: customcraft.admin
    usage: /ccadmin [new]

permissions:
  customcraft.admin:
    description: Allows access to the custom recipe administration menu.
    default: op
